export const MIME_TYPES = new Map([
  ["aac", "audio/aac"],
  ["arc", "application/x-freearc"],
  ["avi", "video/x-msvideo"],
  ["avif", "image/avif"],
  ["css", "text/css"],
  ["csv", "text/csv"],
  ["doc", "application/msword"],
  [
    "docx",
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  ],
  ["gz", "application/gzip"],
  ["gpx", "application/gpx+xml"],
  ["gif", "image/gif"],
  ["html", "text/html"],
  ["ico", "image/vnd.microsoft.icon"],
  ["ics", "text/calendar"],
  ["jpeg", "image/jpeg"],
  ["jpg", "image/jpeg"],
  ["js", "text/javascript"],
  ["json", "application/json; charset=utf-8"],
  ["mid", "audio/x-midi"],
  ["midi", "audio/x-midi"],
  ["mpeg", "video/mpeg"],
  ["png", "image/png"],
  ["pdf", "application/pdf"],
  ["rar", "application/vnd.rar"],
  ["rtf", "application/rtf"],
  ["sh", "application/x-sh"],
  ["svg", "image/svg+xml"],
  ["tar", "application/x-tar"],
  ["tif", "image/tiff"],
  ["tiff", "image/tiff"],
  ["txt", "text/plain"],
  ["usdz", "model/usd"],
  ["wav", "audio/wav"],
  ["weba", "audio/webm"],
  ["webm", "video/webm"],
  ["webmanifest", "application/manifest+json"],
  ["webp", "image/webp"],
  ["xhtml", "application/xhtml+xml"],
  ["xml", "application/xml"],
  ["zip", "application/zip"],
]);
