name = "web"
account_id = "bc4564dd499c0a9b8a7bb79c9bd5ea6d"
main = "./index.js"
compatibility_date = "2023-02-12"
workers_dev = false

r2_buckets  = [
  { binding = "WEB", bucket_name = "web", preview_bucket_name = "web-dev" },
  { binding = "WEB_ASSETS", bucket_name = "web-assets", preview_bucket_name = "web-assets-dev" },
]
